services:
  node-app:
    build: .
    ports:
      - "5000:5000"

    #Overrides initial env variable from Dockerfile
    # environment:
    #   - PORT=5000
    # env_file:
    #   - ./.env

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: exampleUsername
      MONGO_INITDB_ROOT_PASSWORD: examplePassword
    volumes:
      #Named volume - same as anonymous, but can have custom name
      - mongo-db:/data/db

#Declare all named volumes, so all services can use them
volumes:
  mongo-db:
