services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

    #Overrides cmd from dockerfile
    command: npm run dev
