services:
  nginx:
    ports:
      #host:docker
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
      #Pulls these from host env vars
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
