services:
  #nginx service -> redirects requests to node services for load balancing
  nginx:
    image: nginx:stable-alpine
    volumes:
      #bind mount to load nginx configuration without creating custom image, ro - read only
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    depends_on:
      - mongo
    #Overrides initial env variable from Dockerfile
    # environment:
    #   - PORT=5000
    # env_file:
    #   - ./.env

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: exampleUsername
      MONGO_INITDB_ROOT_PASSWORD: examplePassword
    volumes:
      #Named volume - same as anonymous, but can have custom name
      - mongo-db:/data/db

#Declare all named volumes, so all services can use them
volumes:
  mongo-db:
